/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotellerio;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Arzu Shaik
 */
public class Laundry extends javax.swing.JFrame {

    /**
     * Creates new form laundry
     */
    public Laundry() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cust_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        give_more = new javax.swing.JButton();
        cancel_05 = new javax.swing.JButton();
        item_id = new javax.swing.JTextField();
        noof_pieces = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cust_id_err = new javax.swing.JLabel();
        item_id_err = new javax.swing.JLabel();
        pieces_err = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Laundry !! Give Here");

        jLabel2.setText("Customer ID");

        cust_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cust_idKeyTyped(evt);
            }
        });

        jLabel3.setText("Item ID");

        jLabel4.setText("Number of pieces");

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        give_more.setText("Give More");
        give_more.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                give_moreActionPerformed(evt);
            }
        });

        cancel_05.setText("Cancel");
        cancel_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_05ActionPerformed(evt);
            }
        });

        item_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_idActionPerformed(evt);
            }
        });
        item_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                item_idKeyTyped(evt);
            }
        });

        noof_pieces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        noof_pieces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noof_piecesActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotellerio/images/laundry.png"))); // NOI18N

        jLabel6.setText("Washing... Ironing ... Laundry");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cust_id_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cust_id, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(item_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(item_id_err, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noof_pieces, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pieces_err, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(cancel_05)
                .addGap(55, 55, 55)
                .addComponent(give_more)
                .addGap(55, 55, 55)
                .addComponent(done)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cust_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cust_id_err, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(item_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(item_id_err, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(noof_pieces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pieces_err, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_05)
                    .addComponent(give_more)
                    .addComponent(done))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void give_moreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_give_moreActionPerformed
        // TODO add your handling code here:
        String str = String.valueOf(noof_pieces.getSelectedItem());
        if(cust_id.getText().trim().isEmpty() && item_id.getText().trim().isEmpty() && str.isEmpty())
        {
            cust_id_err.setText("*This field is required");
            cust_id_err.setForeground(Color.red);
            item_id_err.setText("*This field is required");
            item_id_err.setForeground(Color.red);
            pieces_err.setText("*This field is required");
            pieces_err.setForeground(Color.red);
        } else if(cust_id.getText().trim().isEmpty())
        {
            cust_id_err.setText("*This field is required");
            cust_id_err.setForeground(Color.red);
            item_id_err.setText("");
            pieces_err.setText("");
        }
        else if(item_id.getText().trim().isEmpty())
        {
            cust_id_err.setText("");
            item_id_err.setForeground(Color.red);
            item_id_err.setText("*This field is required");
            pieces_err.setText("");
        }
        else if(str.isEmpty())
        {
            cust_id_err.setText("");
            pieces_err.setForeground(Color.red);
            item_id_err.setText("");
            pieces_err.setText("*This field is required");
        }
        else {
        int cust_id1 = Integer.valueOf(cust_id.getText());
        int piece_id= Integer.valueOf(item_id.getText());
        String tot_pcs = (String)noof_pieces.getSelectedItem() ;
        int tot_pieces = Integer.parseInt(tot_pcs);
        try{
            Connection con=DBConnect.connect();
            String sqlc="select cust_name from customer_details where cust_Id=?";
            PreparedStatement psc=con.prepareStatement(sqlc);
            psc.setInt(1,cust_id1);
            ResultSet rsc=psc.executeQuery();
            if(rsc.next()){
            String sql1="select price,name from laundry_menu where id=?";
            PreparedStatement ps1=con.prepareStatement(sql1);
            ps1.setInt(1,piece_id);
            ResultSet rs1=ps1.executeQuery();
            float price_of_piece=0;
            String name = new String();
                while(rs1.next())
                        {
                            price_of_piece=rs1.getFloat(1);
                            name=rs1.getString(2);
                        }
                        float t_price = price_of_piece*tot_pieces;
                        String sql="Insert into order_laundry values(?,?,?,?)";
                        PreparedStatement ps=con.prepareStatement(sql);
                        ps.setInt(1,cust_id1);
                        ps.setString(2,name);
                        ps.setInt(3,tot_pieces);
                        ps.setFloat(4,t_price);
			ps.executeUpdate();
                        System.out.println(t_price);
			con.close();}
            else{
                JOptionPane.showMessageDialog(null, "There is no customer with given ID.Please Enter details Again","Display Message",JOptionPane.INFORMATION_MESSAGE);
                    cust_id.setText("");
                    item_id.setText("");
            }
}
catch(Exception e){
    
    System.out.println(e);
}
        finally{
            cust_id.setText("");
            item_id.setText("");
        }}
    }//GEN-LAST:event_give_moreActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
                //new Hotellerio().setVisible(true);

        
    }//GEN-LAST:event_doneActionPerformed

    private void cancel_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_05ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //new Hotellerio().setVisible(true);
    }//GEN-LAST:event_cancel_05ActionPerformed

    private void item_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_idActionPerformed

    private void noof_piecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noof_piecesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noof_piecesActionPerformed

    private void cust_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cust_idKeyTyped
         char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_cust_idKeyTyped

    private void item_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_item_idKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_item_idKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_05;
    private javax.swing.JTextField cust_id;
    private javax.swing.JLabel cust_id_err;
    private javax.swing.JButton done;
    private javax.swing.JButton give_more;
    private javax.swing.JTextField item_id;
    private javax.swing.JLabel item_id_err;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> noof_pieces;
    private javax.swing.JLabel pieces_err;
    // End of variables declaration//GEN-END:variables
}
