/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotellerio;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Arzu Shaik
 */
public class Transport_Facility extends javax.swing.JFrame {

    /**
     * Creates new form Transport_facility
     */
    public Transport_Facility() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        within_city = new javax.swing.JRadioButton();
        outstation = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        cancel_05 = new javax.swing.JButton();
        cust_Id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vehicle_no = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cust_err = new javax.swing.JLabel();
        veh_err = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("book your Transport here!!");

        jLabel2.setText("Customer ID");

        within_city.setText("Within City");
        within_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                within_cityActionPerformed(evt);
            }
        });

        outstation.setText("Out Station");
        outstation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outstationActionPerformed(evt);
            }
        });

        jLabel3.setText("Select Mode");

        confirm.setText("Confirm Booking");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        cancel_05.setText("Cancel");
        cancel_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_05ActionPerformed(evt);
            }
        });

        cust_Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cust_IdKeyTyped(evt);
            }
        });

        jLabel4.setText("Vehicle Number");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotellerio/images/order_ca.png"))); // NOI18N

        jLabel6.setText("You Are Almost There...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outstation)
                                    .addComponent(within_city))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cust_Id)
                                    .addComponent(vehicle_no)
                                    .addComponent(cust_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(veh_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(cancel_05)
                .addGap(98, 98, 98)
                .addComponent(confirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cust_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cust_err, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(within_city)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(outstation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vehicle_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addComponent(veh_err, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm)
                    .addComponent(cancel_05))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void outstationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outstationActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_outstationActionPerformed

    private void within_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_within_cityActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_within_cityActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        if(cust_Id.getText().trim().isEmpty() && vehicle_no.getText().trim().isEmpty())
        {
            cust_err.setText("*This field is required");
            cust_err.setForeground(Color.red);
            veh_err.setText("*This field is required");
            veh_err.setForeground(Color.red);
        }
        else if(cust_Id.getText().trim().isEmpty())
        {
            cust_err.setText("*This field is required");
            cust_err.setForeground(Color.red);
            veh_err.setText("");
        }
        else if(vehicle_no.getText().trim().isEmpty())
        {
            cust_err.setText("");
            veh_err.setText("*This field is required");
            veh_err.setForeground(Color.red);
        }
        else{
            try {
                Connection con1 = DBConnect.connect();
                int customer_id = Integer.valueOf(this.cust_Id.getText());
            String sqlc="select cust_name from customer_details where cust_ID=?";
            PreparedStatement psc = con1.prepareStatement(sqlc);
            psc.setInt(1, customer_id);
            ResultSet rsc = psc.executeQuery();
            if(rsc.next()){
             if(within_city.isSelected())
        {
            try{
                      Class.forName("com.mysql.jdbc.Driver");
                        String url="jdbc:mysql://localhost:3306/hotellerio";
			String user="root";
			String pass="1.414magiC";
	                Connection conn =DriverManager.getConnection(url,user,pass);
                        
                        String sql1="select price from transport_cost where id=?";
                        PreparedStatement ps1 = conn.prepareStatement(sql1);
                        int x=1;
                        ps1.setInt(1,x);
                        ResultSet rs1 = ps1.executeQuery();
                        float cost=0;
                        while(rs1.next())
                        {
                            cost=rs1.getFloat(1);
                        }
                        String str = within_city.getText();
                        String sql="insert into transport_table values(?,?,?,?)";                       
                       PreparedStatement pst=conn.prepareStatement(sql);
                       pst.setInt(1,Integer.valueOf(cust_Id.getText()));
                       pst.setString(2, str);
                       pst.setFloat(3,cost);
                       pst.setString(4, String.valueOf(vehicle_no.getText()));
                       pst.executeUpdate();
                       System.out.println(str);
                       
                       conn.close();
			
		
           }
       catch(Exception e) {
JOptionPane.showMessageDialog(null, e,"Display Message",JOptionPane.INFORMATION_MESSAGE);
                                  }
            finally{
                this.setVisible(false);
                new Transport_Section().setVisible(true);
            }
        }
        
        if(outstation.isSelected())
        {
            try{
                      Class.forName("com.mysql.jdbc.Driver");
                        String url="jdbc:mysql://localhost:3306/hotellerio";
			String user="root";
			String pass="1.414magiC";
	                Connection conn =DriverManager.getConnection(url,user,pass);
                        
                        String sql1="select price from transport_cost where id=?";
                        PreparedStatement ps1 = conn.prepareStatement(sql1);
                        int x=2;
                        ps1.setInt(1,x);
                        ResultSet rs1 = ps1.executeQuery();
                        float cost=0;
                        while(rs1.next())
                        {
                            cost=rs1.getFloat(1);
                        }
                        String str = outstation.getText();
                        String sql="insert into transport_table values(?,?,?,?)";                       
                       PreparedStatement pst=conn.prepareStatement(sql);
                       pst.setInt(1,Integer.valueOf(cust_Id.getText()));
                       pst.setString(2, str);
                       pst.setFloat(3,cost);
                       pst.setString(4, String.valueOf(vehicle_no.getText()));
                       pst.executeUpdate();
                       System.out.println(str);
                       
                       conn.close();
			
		
           }
       catch(Exception e) {
JOptionPane.showMessageDialog(null, e,"Display Message",JOptionPane.INFORMATION_MESSAGE);
                                  }
            finally{
                this.setVisible(false);
                new Transport_Section().setVisible(true);
            }
        }   
            }
            else{
                            JOptionPane.showMessageDialog(null, "There is no customer with given ID.Please Enter details Again","Display Message",JOptionPane.INFORMATION_MESSAGE);

            }}
            catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null, e,"Display Message",JOptionPane.INFORMATION_MESSAGE);
            
                    }
        
        
        
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void cancel_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_05ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Transport_Section().setVisible(true);
    }//GEN-LAST:event_cancel_05ActionPerformed

    private void cust_IdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cust_IdKeyTyped
         char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_cust_IdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transport_Facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transport_Facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transport_Facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transport_Facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transport_Facility().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_05;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField cust_Id;
    private javax.swing.JLabel cust_err;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton outstation;
    private javax.swing.JLabel veh_err;
    private javax.swing.JTextField vehicle_no;
    private javax.swing.JRadioButton within_city;
    // End of variables declaration//GEN-END:variables
}
